"""
Integration tests for object list functionality.

Tests the full workflow: load list → resolve objects → verify resolution rates.
"""
import pytest
from pathlib import Path

from app.object_lists.object_list_loader import ObjectListLoader
from app.catalog.catalog_service import CatalogService


# Path to actual object lists (generated by scripts/generate_object_lists.py)
OBJECT_LISTS_DIR = Path(__file__).parent.parent.parent / 'data' / 'object_lists'


def lists_exist() -> bool:
    """Check if generated list files exist"""
    return (OBJECT_LISTS_DIR / 'messier_110.json').exists()


@pytest.fixture
def real_loader():
    """ObjectListLoader with real CatalogService (uses OpenNGC)"""
    catalog_service = CatalogService()
    return ObjectListLoader(
        lists_dir=OBJECT_LISTS_DIR,
        catalog_service=catalog_service
    )


@pytest.mark.skipif(not lists_exist(), reason="Object list files not generated yet")
class TestMessierListIntegration:
    """Integration tests for Messier catalog"""

    def test_load_messier_list(self, real_loader):
        """Test that Messier list loads successfully"""
        obj_list = real_loader.load_list('messier_110')

        assert obj_list.metadata.name == 'Messier Catalog'
        assert obj_list.metadata.object_count == 110
        assert len(obj_list.objects) == 110

    def test_messier_resolution_rate_above_95_percent(self, real_loader):
        """
        Quality gate: At least 95% of Messier objects must resolve.
        
        This ensures our canonical_ids match what CatalogService expects.
        """
        obj_list = real_loader.load_list('messier_110')
        result = real_loader.resolve_objects(obj_list)

        print(f"\nMessier resolution: {result.success_count}/{result.total_count}")
        if result.failures:
            print("Failures:")
            for f in result.failures:
                print(f"  - {f.name} ({f.canonical_id}): {f.reason}")

        assert result.success_rate >= 95.0, (
            f"Messier resolution rate {result.success_rate:.1f}% is below 95% threshold. "
            f"Failures: {[f.name for f in result.failures]}"
        )

    def test_messier_objects_have_valid_data(self, real_loader):
        """Test that resolved Messier objects have required fields"""
        obj_list = real_loader.load_list('messier_110')
        result = real_loader.resolve_objects(obj_list)

        # Spot check some well-known objects
        m31 = next((obj for obj in result.resolved if 'M31' in obj.name or obj.canonical_id == 'NGC0224'), None)
        assert m31 is not None, "M31 should be resolved"
        assert m31.magnitude < 10, "M31 should have reasonable magnitude"
        assert m31.ra > 0, "M31 should have RA"
        assert m31.dec > 0, "M31 should have positive Dec"


@pytest.mark.skipif(not lists_exist(), reason="Object list files not generated yet")
class TestCaldwellListIntegration:
    """Integration tests for Caldwell catalog"""

    def test_load_caldwell_list(self, real_loader):
        """Test that Caldwell list loads successfully"""
        obj_list = real_loader.load_list('caldwell_109')

        assert obj_list.metadata.name == 'Caldwell Catalog'
        # May be less than 109 if some objects missing from OpenNGC
        assert obj_list.metadata.object_count >= 100

    def test_caldwell_resolution_rate_above_95_percent(self, real_loader):
        """Quality gate: At least 95% of Caldwell objects must resolve."""
        obj_list = real_loader.load_list('caldwell_109')
        result = real_loader.resolve_objects(obj_list)

        print(f"\nCaldwell resolution: {result.success_count}/{result.total_count}")
        if result.failures:
            print("Failures:")
            for f in result.failures:
                print(f"  - {f.name} ({f.canonical_id}): {f.reason}")

        assert result.success_rate >= 95.0, (
            f"Caldwell resolution rate {result.success_rate:.1f}% is below 95% threshold. "
            f"Failures: {[f.name for f in result.failures]}"
        )


@pytest.mark.skipif(not lists_exist(), reason="Object list files not generated yet")
class TestSolarSystemListIntegration:
    """Integration tests for Solar System objects"""

    def test_load_solar_system_list(self, real_loader):
        """Test that Solar System list loads successfully"""
        obj_list = real_loader.load_list('solar_system')

        assert obj_list.metadata.name == 'Solar System'
        assert obj_list.metadata.object_count == 9

    @pytest.mark.skip(reason="Solar System resolution requires Horizons API - may be slow/unreliable")
    def test_solar_system_resolution(self, real_loader):
        """Test Solar System object resolution via Horizons"""
        obj_list = real_loader.load_list('solar_system')
        result = real_loader.resolve_objects(obj_list)

        # Solar System objects resolve via Horizons
        print(f"\nSolar System resolution: {result.success_count}/{result.total_count}")
        assert result.success_count >= 5, "At least 5 solar system objects should resolve"


@pytest.mark.skipif(not lists_exist(), reason="Object list files not generated yet")
class TestAllListsQualityGate:
    """
    Quality gate tests for all shipped object lists.
    
    These tests ensure data quality before release.
    """

    def test_all_shipped_lists_meet_resolution_threshold(self, real_loader):
        """
        Quality gate: All shipped lists must have ≥95% resolution rate.
        
        This is a critical data quality check.
        """
        lists = real_loader.get_available_lists()
        
        # Skip solar_system as it uses Horizons API
        dso_lists = [l for l in lists if 'solar' not in l.list_id.lower()]
        
        failures = []
        for list_meta in dso_lists:
            obj_list = real_loader.load_list(list_meta.list_id)
            result = real_loader.resolve_objects(obj_list)
            
            if result.success_rate < 95.0:
                failures.append(
                    f"{list_meta.name}: {result.success_rate:.1f}% "
                    f"({result.failure_count} failures)"
                )
        
        assert not failures, (
            f"Lists below 95% resolution threshold:\n" + "\n".join(failures)
        )

    def test_all_lists_have_valid_metadata(self, real_loader):
        """Test that all lists have required metadata fields"""
        lists = real_loader.get_available_lists()
        
        for list_meta in lists:
            assert list_meta.list_id, f"List missing list_id"
            assert list_meta.name, f"List {list_meta.list_id} missing name"
            assert list_meta.object_count > 0, f"List {list_meta.list_id} is empty"

    def test_no_duplicate_canonical_ids_within_list(self, real_loader):
        """Test that lists don't have duplicate objects"""
        lists = real_loader.get_available_lists()
        
        for list_meta in lists:
            obj_list = real_loader.load_list(list_meta.list_id)
            canonical_ids = [obj.canonical_id for obj in obj_list.objects]
            
            duplicates = [cid for cid in canonical_ids if canonical_ids.count(cid) > 1]
            assert not duplicates, (
                f"List {list_meta.name} has duplicate canonical_ids: {set(duplicates)}"
            )
